Pierwsza wersja encji User
pplutap/JDP-1901-01 pull request #11
Opened 2019-02-07 09:50 UTC by lukaszmazurkiewicz

Klasy UserMapper/UserService/UserRepository są wstępnie tylko stworzone bo o ile się nie mylę to potrzebne będą dopiero do rzeczywistej implementacji controllera.

2019-02-07 10:11 UTC, przemyslawkrawczynski commented on src/main/java/com/kodilla/ecommercee/mapper/UserMapper.java
> +                .map(u -> new UserDto(u.getId(), u.getUsername(), u.getStatus(), u.getUserKey()))
tutaj ewentualnie można użyć już metody mapToDto..

2019-02-07 10:14 UTC, przemyslawkrawczynski commented
Generalnie mógłbyś zaimplementować, bo jak wszyscy skończą Encje i zmargujemy do mastera, będzie łatwiej i w szerszym zakresie można przeprowadzić testy jednostkowe...

2019-02-08 16:18 UTC, coder-msl approved these changes
W mojej ocenie jest OK :) nie dopatrzyłem się wielkich uchybień...

2019-02-08 16:18 UTC, haker-msl commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +
ta pusta linia jest tutaj celowo? Aż się zastanawiałem co to za lista bez mapowania przez chwilę :D dopiero później zauważyłem adnotację powyżej...

2019-02-08 16:34 UTC, coder-msl requested changes

2019-02-08 16:34 UTC, haker-msl commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    private List<Order> orders = new ArrayList<>();
celowo nie ustawiasz tej listy w konstruktorze ? W encji Cart  leci w konstruktorze lista... tutaj nie :) pytanie czy ta różnica jest uzasadniona? Jeśli robimy konstruktor bezparametrowy i konstruktor, który ustawia wszystkie parametry to raczej to powinno być.Tak musimy stworzyć entity przez konstruktor i listę zasilić osobno pod wywołaniem konstruktora.

2019-02-08 16:34 UTC, haker-msl commented on src/main/java/com/kodilla/ecommercee/exception/UserNotFoundException.java
> +public class UserNotFoundException extends Exception{
pierdoła bo po Exception nie ma spacji przed {

2019-02-08 17:53 UTC, kszubra commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    public User(Long id, String username, String status, Long userKey) {
@haker-msl ma rację, w konstruktorze nie powinno być również listy orderów jako parametru? Z takim konstruktorem może być potem problem z mapperem

2019-02-09 00:22 UTC, lukaszmazurkiewicz commented
Poprawki wprowadzone zgodnie z sugestiami ;]

2019-02-09 18:18 UTC, coder-msl approved these changes

2019-02-09 18:20 UTC, merged