Bug jdp 190101 33
pplutap/JDP-1901-01 pull request #15
Opened 2019-02-09 14:15 UTC by radion358

2019-02-10 10:04 UTC, przemyslawkrawczynski requested changes

2019-02-10 10:04 UTC, przemyslawkrawczynski commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +            joinColumns = {@JoinColumn(name = "CART_ID", referencedColumnName = "ID")},
Przy tym zapisie będzie jeszcze brakować oznaczenia kolumny przy @Id - zarówno w product, jak i tutaj. Przynajmniej na moim lok branchu nie radzi sobie hibernate.

2019-02-10 10:04 UTC, przemyslawkrawczynski commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    private List<Product> products;
Tutaj musi być wywalona lista a ma być pole Cart cart - i relacja do jednostronna @OneToOne przy geterze
Edit: dzięki za czujność kszubra:)

2019-02-10 10:04 UTC, przemyslawkrawczynski commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +        return products;
Do wywalenia ma być mapowanie na obiekt Cart z relacja @onetoOne - tak jak ustaliliśmy

2019-02-10 11:37 UTC, kszubra commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +            joinColumns = {@JoinColumn(name = "CART_ID", referencedColumnName = "ID")},
Od siebie daję tylko informacje, że u mnie build wyszedł, ale musi działać u wszystkich

2019-02-10 13:01 UTC, kszubra commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    private List<Product> products;
:)

2019-02-10 16:08 UTC, przemyslawkrawczynski reviewed
Na moje oko jest zgodnie z tym wszystkim co miało być. Jeśli projekt wstaje i aplikacja się buduje żeby testy robić to ok, nie mogę sprawdzić obecnie pisze z tel. Proszę mentorow o ostateczna ocenę kodu i zgodę na mergowanie.

2019-02-10 20:51 UTC, przemyslawkrawczynski approved these changes

2019-02-10 20:54 UTC, kszubra approved these changes
Według mnie ok, u mnie się buduje

2019-02-11 14:01 UTC, MARudnicki approved these changes
Wyglada OK

2019-02-11 14:43 UTC, merged