Pierwsze wprawki do testów encji.
pplutap/JDP-1901-01 pull request #16
Opened 2019-02-11 21:00 UTC by lukaszmazurkiewicz

- Z konstruktora Usera usunąłem jednak List<Order> ponieważ w Orderze w konstruktorze był User i tutaj mieliśmy chyba konflikt? 
- Testy są na ten moment szczątkowe bo chciałem sprawdzić czy zmierzam w dobrym kierunku w ogóle? A  test  testFindById nie działa w ogóle jeszcze.

2019-02-12 10:09 UTC, aleksanderkot00 commented
Moim zdaniem brakuje czyszczenia po testach. Teraz użytkownicy zapisani w teście w bazie danych zostaną tam.

2019-02-12 11:05 UTC, lukaszmazurkiewicz commented
No właśnie akurat wczoraj czytałem na którymś kanale na komunikatorze od któregoś mentora, że właśnie adnotacja @Transactional do tego służy. Robi rollback transakcji po teście.

2019-02-12 11:06 UTC, radoslaw-dauksza reviewed
Wygląda ok. Nie wiem co ci doradzić z tym testem, chyba powinieneś podpytać mentorów. Zauważyłem że u mnie po uruchomieniu aplikacji nie tworzy się tabela users.

2019-02-12 14:25 UTC, aleksanderkot00 commented
Masz racje. @Transactional usuwa zmiany.

2019-02-12 15:43 UTC, lukaszmazurkiewicz commented
Kolejne zmiany w encji User, testy są jeszcze do rozbudowania ale na ten moment wszystkie trzy przechodzą.

2019-02-13 20:48 UTC, radoslaw-dauksza requested changes

2019-02-13 20:48 UTC, radion358 commented on src/test/java/com/kodilla/ecommercee/domain/UserTestSuite.java
> +        Assert.assertEquals(2, orders.size());
Jeśli w bazie będą inne zamówienia to assertEquals zwróci false.

2019-02-13 20:48 UTC, radion358 commented on src/test/java/com/kodilla/ecommercee/domain/UserTestSuite.java
> +        Optional<User> testUser = userRepository.findById(testId);
Myślę że zamiast tworzyć zmienną testId można zrobić findById(user2.getId()).

2019-02-13 20:48 UTC, radion358 commented on src/test/java/com/kodilla/ecommercee/domain/UserTestSuite.java
> +        Assert.assertEquals(3, users.size());
Jeśli w bazie będą inni użytkownicy to assertEquals zwróci false.

2019-02-13 20:48 UTC, radion358 commented on src/test/java/com/kodilla/ecommercee/domain/UserTestSuite.java
> +        Assert.assertEquals(4L, userRepository.count());
Jeśli w bazie będą inni użytkownicy to assertEquals zwróci false.

2019-02-13 21:09 UTC, lukaszmazurkiewicz commented
Poprawki od @radion358 wprowadzone

2019-02-13 22:05 UTC, radoslaw-dauksza approved these changes

2019-02-13 22:37 UTC, kszubra approved these changes
Wydaje mi się, że ok. Testy lokalnie zaliczone

2019-02-14 12:15 UTC, aleksanderkot00 approved these changes
U mnie też testy przechodzą i wszytko wygląda dobrze.

2019-02-17 13:07 UTC, coder-msl approved these changes
Generalnie OK. Natomiast ciężko mi się to sprawdza. Nie mam powiązania taska z pull-requestem ani w drugą stronę. Nie mogę do końca rzetelnie sprawdzić zadania jeśli nie wiadomo co było jego treścią. Czytając headline "pierwsze poprawki" mogę założyć, że będą kolejne... a może nie? No chyba, że gdzieś przeoczyłem powiązanie ticketa z PR czy w drugą stronę? W każdym razie listę zadań w JIRA mam pustą :/

2019-02-17 17:04 UTC, lukaszmazurkiewicz commented
Rzeczywiście, mój błąd, zapomniałem wyedytować tytułu PR na bardziej aktualny.

2019-02-17 17:05 UTC, merged