Jdp190101 22 group controller impl
pplutap/JDP-1901-01 pull request #22
Opened 2019-02-18 21:32 UTC by kszubra

2019-02-19 08:14 UTC, MARudnicki requested changes

2019-02-19 08:14 UTC, MARudnicki commented on src/main/java/com/kodilla/ecommercee/exception/GroupNotFoundException.java
> +public class GroupNotFoundException extends RuntimeException {
Warto dorzucić adnotacje `@ResponseStatus(code ...)`. Wtedy przy wyrzuceniu exception'a, klient dostanie np. 404 (blad zapytania), zamiast 500 (blad serwera)

2019-02-19 10:41 UTC, aleksanderkot00 requested changes

2019-02-19 10:41 UTC, aleksanderkot00 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
>      @PutMapping(value = "update")
Zgodnie z tym, co jest w readme fronendu zapytania update mają być chyba typu Patch, a nie Put.

2019-02-19 10:41 UTC, aleksanderkot00 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
>      @GetMapping(value = "id/{id}")
Tutaj też zgonie z readme frontu powinno chyba być @GetMapping(value = "{id}")

2019-02-19 13:01 UTC, kszubra commented on src/main/java/com/kodilla/ecommercee/exception/GroupNotFoundException.java
> +public class GroupNotFoundException extends RuntimeException {
Dzięki, dodane :)

2019-02-19 13:04 UTC, kszubra commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
>      @PutMapping(value = "update")
Faktycznie, pisałem ten kod zanim dostaliśmy link do frontu. Poprawiłem.

2019-02-19 15:17 UTC, kszubra commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
>      @PutMapping(value = "update")
Już zmienione. Pisałem ten kod zanim dostaliśmy fronta

2019-02-19 15:18 UTC, kszubra commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
>      @GetMapping(value = "id/{id}")
Też zmienione

2019-02-19 22:56 UTC, aleksanderkot00 approved these changes

2019-02-20 04:18 UTC, radoslaw-dauksza approved these changes

2019-02-20 06:35 UTC, MARudnicki approved these changes

2019-02-20 11:19 UTC, merged